# Generated by Django 3.2.9 on 2022-04-11 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysDept',
            fields=[
                ('create_by', models.CharField(blank=True, max_length=256, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_by', models.CharField(blank=True, max_length=256, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('dept_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='部门ID')),
                ('parent_id', models.IntegerField(default=0, verbose_name='父部门ID')),
                ('ancestors', models.CharField(default=None, max_length=128, verbose_name='祖级列表')),
                ('dept_name', models.CharField(default=None, max_length=128, verbose_name='部门名称')),
                ('order_num', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('leader', models.CharField(default=None, max_length=64, verbose_name='负责人')),
                ('phone', models.CharField(default=None, max_length=64, verbose_name='联系电话')),
                ('email', models.CharField(default=None, max_length=64, verbose_name='邮箱')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '停用')], default='0', max_length=1, verbose_name='部门状态')),
            ],
            options={
                'verbose_name': '部门表',
                'db_table': 'sys_dept',
            },
        ),
        migrations.CreateModel(
            name='SysDictData',
            fields=[
                ('create_by', models.CharField(blank=True, max_length=256, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_by', models.CharField(blank=True, max_length=256, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('dict_code', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('dict_sort', models.IntegerField(default=0, verbose_name='字典排序')),
                ('dict_label', models.CharField(default=None, max_length=64, verbose_name='字典标签')),
                ('dict_value', models.CharField(default=None, max_length=1024, verbose_name='字典键值')),
                ('dict_type', models.CharField(default=None, max_length=64, verbose_name='字典类型')),
                ('css_class', models.CharField(default=None, max_length=64, verbose_name='样式属性（其他样式扩展）')),
                ('list_class', models.CharField(default=None, max_length=64, verbose_name='表格回显样式')),
                ('is_default', models.CharField(default='N', max_length=16, verbose_name='表格回显样式')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '停用')], default='0', max_length=1, verbose_name='字典状态')),
            ],
            options={
                'verbose_name': '字典数据表',
                'db_table': 'sys_dict_data',
            },
        ),
        migrations.CreateModel(
            name='SysDictType',
            fields=[
                ('create_by', models.CharField(blank=True, max_length=256, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_by', models.CharField(blank=True, max_length=256, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('dict_id', models.AutoField(primary_key=True, serialize=False, verbose_name='字典主键')),
                ('dict_name', models.CharField(default=None, max_length=64, verbose_name='字典名称')),
                ('dict_type', models.CharField(default=None, max_length=64, verbose_name='字典类型')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '停用')], default='0', max_length=1, verbose_name='字典类型状态')),
            ],
            options={
                'verbose_name': '字典类型表',
                'db_table': 'sys_dict_type',
            },
        ),
        migrations.CreateModel(
            name='SysMenu',
            fields=[
                ('create_by', models.CharField(blank=True, max_length=256, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_by', models.CharField(blank=True, max_length=256, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('menu_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='菜单ID')),
                ('menu_name', models.CharField(max_length=64, verbose_name='菜单名称')),
                ('parent_id', models.IntegerField(default=0, verbose_name='父菜单ID')),
                ('order_num', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('path', models.CharField(default=None, max_length=256, verbose_name='路由地址')),
                ('component', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='组件路径')),
                ('menu_type', models.CharField(choices=[('M', '目录'), ('C', '菜单'), ('L', '外链')], max_length=1, verbose_name='菜单类型')),
                ('visible', models.CharField(choices=[('0', '显示'), ('1', '隐藏')], default='0', max_length=1, verbose_name='菜单状态')),
                ('perms', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name='权限标识')),
                ('icon', models.CharField(default='#', max_length=256, verbose_name='菜单图标')),
                ('is_frame', models.IntegerField(default=1, verbose_name='是否为外链（0是 1否）')),
                ('is_cache', models.IntegerField(default=0, verbose_name='是否缓存（0缓存 1不缓存）')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '停用')], default=0, max_length=1, verbose_name='菜单状态')),
            ],
            options={
                'verbose_name': '菜单表',
                'db_table': 'sys_menu',
            },
        ),
        migrations.CreateModel(
            name='SysPost',
            fields=[
                ('create_by', models.CharField(blank=True, max_length=256, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_by', models.CharField(blank=True, max_length=256, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('post_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='岗位ID')),
                ('post_code', models.CharField(max_length=64, verbose_name='岗位编码')),
                ('post_name', models.CharField(max_length=64, verbose_name='岗位名称')),
                ('post_sort', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '停用')], default='0', max_length=1, verbose_name='岗位状态')),
            ],
            options={
                'verbose_name': '岗位表',
                'db_table': 'sys_post',
            },
        ),
        migrations.CreateModel(
            name='SysRole',
            fields=[
                ('create_by', models.CharField(blank=True, max_length=256, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_by', models.CharField(blank=True, max_length=256, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('role_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='角色ID')),
                ('role_name', models.CharField(default='common', max_length=64, verbose_name='角色名')),
                ('role_key', models.CharField(default='common', max_length=64, verbose_name='角色权限字符')),
                ('role_sort', models.IntegerField(default=-1, verbose_name='角色顺序')),
                ('data_scope', models.CharField(choices=[('1', '全部数据权限'), ('2', '自定义数据权限'), ('3', '本部门数据权限'), ('4', '本部门及以下数据权限')], default=1, max_length=1, verbose_name='数据范围')),
                ('dept_check_strictly', models.IntegerField(default=1, verbose_name='部门树选择项是否关联显示')),
                ('menu_check_strictly', models.IntegerField(default=1, verbose_name='菜单树选择项是否关联显示')),
                ('status', models.CharField(choices=[('1', '正常'), ('2', '停用')], default='0', max_length=1, verbose_name='角色状态')),
            ],
            options={
                'verbose_name': '岗位表',
                'db_table': 'sys_role',
            },
        ),
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('create_by', models.CharField(blank=True, max_length=256, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_by', models.CharField(blank=True, max_length=256, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('user_id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='用户ID')),
                ('user_name', models.CharField(max_length=256, verbose_name='用户账号')),
                ('nick_name', models.CharField(max_length=256, verbose_name='用户昵称')),
                ('email', models.CharField(default=None, max_length=128, verbose_name='用户邮箱')),
                ('phone_number', models.CharField(max_length=128, verbose_name='手机号码')),
                ('sex', models.CharField(choices=[('0', '男'), ('1', '女'), ('2', '未知')], default='2', max_length=1, verbose_name='用户性别')),
                ('avatar', models.CharField(default=None, max_length=256, verbose_name='用户头像')),
                ('password', models.CharField(max_length=512, verbose_name='用户密码')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '停用')], default='0', max_length=1, verbose_name='账号状态')),
                ('login_ip', models.CharField(default=None, max_length=64, verbose_name='最后登录IP')),
                ('login_date', models.DateTimeField(auto_now=True, verbose_name='最后登录时间')),
                ('dept', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.sysdept', verbose_name='部门')),
            ],
            options={
                'verbose_name': '用户表',
                'db_table': 'sys_user',
            },
        ),
        migrations.CreateModel(
            name='SysRoleMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sysmenu', verbose_name='菜单ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sysrole', verbose_name='角色ID')),
            ],
            options={
                'verbose_name': '角色菜单表',
                'db_table': 'sys_role_menu',
            },
        ),
        migrations.AddField(
            model_name='sysmenu',
            name='roles',
            field=models.ManyToManyField(through='core.SysRoleMenu', to='core.SysRole'),
        ),
    ]
