# Generated by Django 3.2.9 on 2022-04-11 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sysuser',
            old_name='nick_name',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='sysuser',
            old_name='user_name',
            new_name='username',
        ),
    ]
