# Generated by Django 3.2.9 on 2022-04-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sysuserpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysuser',
            name='posts',
            field=models.ManyToManyField(through='core.SysUserPost', to='core.SysPost', verbose_name='岗位'),
        ),
        migrations.AddField(
            model_name='sysuser',
            name='roles',
            field=models.ManyToManyField(through='core.SysUserRole', to='core.SysRole', verbose_name='角色'),
        ),
    ]
