# Generated by Django 3.2.9 on 2022-04-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220411_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='手机号码'),
        ),
    ]
