# Generated by Django 3.2.9 on 2022-04-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220413_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysrole',
            name='depts',
            field=models.ManyToManyField(to='core.SysDept', verbose_name='部门'),
        ),
        migrations.AlterField(
            model_name='sysrole',
            name='dept_check_strictly',
            field=models.BooleanField(default=True, verbose_name='部门树选择项是否关联显示'),
        ),
        migrations.AlterField(
            model_name='sysrole',
            name='menu_check_strictly',
            field=models.BooleanField(default=True, verbose_name='菜单树选择项是否关联显示'),
        ),
        migrations.AlterField(
            model_name='sysrole',
            name='status',
            field=models.CharField(choices=[('0', '正常'), ('1', '停用')], default='0', max_length=1, verbose_name='角色状态'),
        ),
    ]
