# Generated by Django 3.2.9 on 2022-04-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sysmenu_affix'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysmenu',
            name='breadcrumb',
            field=models.BooleanField(default=True, verbose_name='是否在面包屑中显示'),
        ),
    ]
