# Generated by Django 3.2.9 on 2022-04-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sysmenu_breadcrumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysmenu',
            name='is_cache',
            field=models.BooleanField(default=False, verbose_name='是否缓存'),
        ),
    ]
