# Generated by Django 3.2.9 on 2022-04-19 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_sysmenu_is_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysdictdata',
            name='dict_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.sysdicttype', verbose_name='字典类型'),
        ),
    ]
