# Generated by Django 3.2.9 on 2022-04-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_sysdictdata_dict_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysArgs',
            fields=[
                ('create_by', models.CharField(blank=True, max_length=256, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_by', models.CharField(blank=True, max_length=256, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('arg_id', models.AutoField(primary_key=True, serialize=False, verbose_name='参数ID')),
                ('arg_name', models.CharField(max_length=32, verbose_name='参数名')),
                ('arg_key', models.CharField(max_length=128, verbose_name='参数的键')),
                ('arg_value', models.CharField(max_length=128, verbose_name='参数的值')),
                ('built_in', models.BooleanField(default=True, verbose_name='是否系统内置')),
            ],
            options={
                'verbose_name': '系统参数表',
                'db_table': 'sys_args',
            },
        ),
        migrations.AlterField(
            model_name='sysdictdata',
            name='css_class',
            field=models.CharField(blank=True, default=None, max_length=64, verbose_name='样式属性（其他样式扩展）'),
        ),
    ]
