# Generated by Django 3.2.9 on 2022-04-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20220420_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysdictdata',
            name='css_class',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='样式属性（其他样式扩展）'),
        ),
    ]
