# Generated by Django 3.2.9 on 2022-04-20 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_sysdictdata_css_class'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SysArgs',
            new_name='SysConfig',
        ),
        migrations.AlterModelTable(
            name='sysconfig',
            table='sys_config',
        ),
    ]
