# Generated by Django 3.2.9 on 2022-04-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20220420_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sysconfig',
            old_name='arg_id',
            new_name='config_id',
        ),
        migrations.RenameField(
            model_name='sysconfig',
            old_name='arg_key',
            new_name='config_key',
        ),
        migrations.RenameField(
            model_name='sysconfig',
            old_name='arg_name',
            new_name='config_name',
        ),
        migrations.RenameField(
            model_name='sysconfig',
            old_name='arg_value',
            new_name='config_value',
        ),
        migrations.RemoveField(
            model_name='sysconfig',
            name='built_in',
        ),
        migrations.AddField(
            model_name='sysconfig',
            name='config_type',
            field=models.CharField(choices=[('Y', '是'), ('N', '否')], default='Y', max_length=1, verbose_name='系统内置'),
        ),
    ]
