# Generated by Django 3.2.9 on 2022-04-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20220421_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysOperationLog',
            fields=[
                ('create_by', models.CharField(blank=True, max_length=256, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_by', models.CharField(blank=True, max_length=256, null=True, verbose_name='更新者')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='日志编号')),
                ('title', models.CharField(max_length=512, verbose_name='系统模块')),
                ('business_type', models.CharField(max_length=32, verbose_name='操作类型')),
                ('request_method', models.CharField(max_length=32, verbose_name='请求方式')),
                ('request_param', models.TextField(verbose_name='请求参数')),
                ('json_result', models.TextField(verbose_name='返回参数')),
                ('error_msg', models.TextField(verbose_name='错误消息')),
                ('ip', models.GenericIPAddressField(verbose_name='操作地址')),
                ('op_location', models.CharField(max_length=512, verbose_name='操作地点')),
                ('operator', models.CharField(max_length=256, verbose_name='操作人员')),
                ('status', models.CharField(choices=[('0', '成功'), ('1', '失败')], max_length=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '操作日志表',
                'db_table': 'sys_operation_log',
            },
        ),
        migrations.AlterField(
            model_name='sysnotice',
            name='status',
            field=models.CharField(choices=[('0', '正常'), ('1', '关闭')], max_length=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='sysuser',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), to='core.sysdept', verbose_name='部门'),
        ),
    ]
