# Generated by Django 3.2.9 on 2022-04-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_rename_op_location_sysoperationlog_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysoperationlog',
            name='error_msg',
            field=models.TextField(null=True, verbose_name='错误消息'),
        ),
    ]
