# Generated by Django 3.2.9 on 2022-04-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_sysoperationlog_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysoperationlog',
            name='method',
            field=models.TextField(default=None, null=True, verbose_name='操作方法'),
        ),
    ]
