# Generated by Django 3.2.9 on 2022-04-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_sysoperationlog_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysoperationlog',
            name='request_url',
            field=models.TextField(default=None, null=True, verbose_name='请求url'),
        ),
    ]
